### ISSUE TITLE
esp32-box-lite display configuration in esphome/platformio

### ISSUE THREAD

**Issue by nebulous** [nebulous/infinitesp#2]
I'm trying to get my esp32-s3-box-lite's display to work via esphome using the built-in [st7789v](https://esphome.io/components/display/st7789v.html) configuration. I'm hoping that someone more familiar with display configuration in esphome can identify whatever it is I'm missing.

I can confirm that the display works correctly when compiling [example apps](https://github.com/espressif/esp-box/tree/master/examples/image_display) directly using esp-idf, but ideally I'd like to keep this in the esphome ecosystem to make things simpler for me and anyone else who going to use it.

What follows is my configuration (common just contains wifi ssid/creds common to all of my esphome projects)
pin numbers are gleaned from the [esp-box bsp files](https://github.com/espressif/esp-box/blob/master/components/bsp/src/boards/esp32_s3_box_lite.c#L51), which corroborate with the [published device schematics](https://github.com/espressif/esp-box/blob/master/hardware/esp32_s3_box_lite_MB_V1.1/schematic/SCH_ESP32-S3-BOX-Lite_MB_V1.1_20211221.pdf) like so: 

![image](https://user-images.githubusercontent.com/177510/211406903-fab91c5c-957d-4099-93bf-ad0329926dd3.png)

```yaml

substitutions:
  name: infinitesp

esphome:
  name: $name

esp32:
  board: esp32s3box
  variant: esp32s3
  framework:
    type: arduino
    version: dev
    platform_version: 5.3.0

<<: !include common.yaml

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: adc
    pin: GPIO1
    name: "front buttons"

i2c:
  scl: GPIO18
  sda: GPIO8
  scan: true

psram:
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6


display:
  - platform: st7789v
    model: custom
    backlight_pin:
        number: GPIO45
        inverted: true
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin: GPIO48
    width: 320
    height: 240
    offset_height: 0
    offset_width: 0
    lambda: |-
      it.rectangle(0,0,it.get_width(),it.get_height(),id(c_green));
      //it.image(0, 0, id(my_image));

color:
  - id: c_green
    red: 0%
    green: 100%
    blue: 0%

image:
  - file: "image.png"
    id: my_image
    type: RGB24
```
